import "./globals.css";
import { ThemeProvider } from "next-themes";
import { UserContextProvider } from "@/context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserContextProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            {children}
          </ThemeProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
